### ISSUE TITLE
Can't get circles to work

### ISSUE THREAD

**Issue by loryanstrant** [ShunichiSan/HomeAssistantApplianceCard#7]
I can't for the life of me get the circles to work, and I wonder if there's something missing from the example YAML.
I had a look at issue #2 but it's not the same issue.

Here's what my card looks like in the visual editor:

![Image](https://github.com/user-attachments/assets/141eebf0-af1e-422c-a955-e1371e8cfcd6)

You'll notice that the "custom:circle-sensor-card" is saying "Unknown type" underneath it.
The thing is that it's not an issue with the circle card, or the sensor being used because if I isolate that it works fine:

![Image](https://github.com/user-attachments/assets/cfed84e5-4293-41c3-b19f-731a3567c6f6)

This is what the code for one of my cards is like:
```
type: picture-elements
elements:
  - type: state-label
    entity: sensor.dryer_remaining_time
    style:
      right: 1%
      top: 12.5%
      color: "#99d6ff"
  - type: custom:circle-sensor-card
    fill: rgba(66, 66, 66)
    max: 100
    entity: sensor.dryer_progress
    font_style:
      font-size: 0
      text-align: center
    show_card: false
    stroke_width: 15
    style:
      left: 42%
      top: 56%
  - type: state-label
    entity: sensor.dryer_activity
    style:
      left: 50%
      top: 91%
grid_options:
  columns: 4
  rows: auto
image: /api/image/serve/dd3cf4e3d61048b9a90ac06867595356/512x512
title: Dryer
```
